### ISSUE TITLE
Pretrained weights problem.

### ISSUE THREAD

**Issue by Byronnar** [Dootmaan/MT-UNet#10]
How to get the pretrained weights in custom datasets?  Not ACDC or Synapse. Thanks, Looking forward to your reply.
@Dootmaan

**Comment by Byronnar** [comment]
```
Update 2022/01/03
It should be mentioned that we are currently conducting some statistical evaluations on our model and these results will be also made public on this site.

Click here for the pretrained weights for Synapse.

Click here for the pretrained weights for ACDC. The authors of TransUnet did not provide the split of ACDC dataset. Therefore, we conducted all the ACDC experiments based on our own dataset split.
```
And this two pretrained weights are same,   ACDC and Synapse use the same pretrained weight?

**Comment by Dootmaan** [comment]
> ```
> Update 2022/01/03
> It should be mentioned that we are currently conducting some statistical evaluations on our model and these results will be also made public on this site.
> 
> Click here for the pretrained weights for Synapse.
> 
> Click here for the pretrained weights for ACDC. The authors of TransUnet did not provide the split of ACDC dataset. Therefore, we conducted all the ACDC experiments based on our own dataset split.
> ```
> 
> And this two pretrained weights are same, ACDC and Synapse use the same pretrained weight?

Sorry about this mistake. We have corrected the ACDC link in readme.

**Comment by Byronnar** [comment]
> 

Thank you so much!  And I have a question, the pretrained weights just is the trained model on ACDC or Synapse? Not in other datasets?  Which the pretrained weight used in your paper to get the best results?

**Comment by Byronnar** [comment]
```
Update 2022/01/04
We have further trained our MT-UNet and it turns out to have a better result on Synapse with 79.20% DSC. We have changed the pretrained weights of Synapse to this version and will also update the results in our paper.
```
This result use any pretrained model?

**Comment by Dootmaan** [comment]
> > 
> 
> Thank you so much! And I have a question, the pretrained weights just is the trained model on ACDC or Synapse? Not in other datasets? Which the pretrained weight used in your paper to get the best results?

Hi there. Thank u for your question. However, I think there may be a little misunderstanding here. 
The so-called 'pretrained weights' in this repo is JUST the one we used in the paper to have the results. Unlike Swin-Unet or TransUnet, our model does NOT need any ViT pretrained weights, and it is trained from scratch. We make these two weights public so peers can verify our experimental results. If you would like to use MT-Unet for other datasets, you can train it from scratch by yourself or you can use either uploaded file in this repo as initial weights for your training.

**Comment by Byronnar** [comment]
> > > 
> > 
> > 
> > Thank you so much! And I have a question, the pretrained weights just is the trained model on ACDC or Synapse? Not in other datasets? Which the pretrained weight used in your paper to get the best results?
> 
> Hi there. Thank u for your question. However, I think there may be a little misunderstanding here. The so-called 'pretrained weights' in this repo is JUST the one we used in the paper to have the results. Unlike Swin-Unet or TransUnet, our model does NOT need any ViT pretrained weights, and it is trained from scratch. We make these two weights public so peers can verify our experimental results. If you would like to use MT-Unet for other datasets, you can train it from scratch by yourself or you can use either uploaded file in this repo as initial weights for your training.

Alright, Thanks foy your patient  answer, I understood it. Could you please share me the latest training code, my email address is Byronnar@163.com, Thank u su much.

**Comment by Dootmaan** [comment]
> > > > 
> > > 
> > > 
> > > Thank you so much! And I have a question, the pretrained weights just is the trained model on ACDC or Synapse? Not in other datasets? Which the pretrained weight used in your paper to get the best results?
> > 
> > 
> > Hi there. Thank u for your question. However, I think there may be a little misunderstanding here. The so-called 'pretrained weights' in this repo is JUST the one we used in the paper to have the results. Unlike Swin-Unet or TransUnet, our model does NOT need any ViT pretrained weights, and it is trained from scratch. We make these two weights public so peers can verify our experimental results. If you would like to use MT-Unet for other datasets, you can train it from scratch by yourself or you can use either uploaded file in this repo as initial weights for your training.
> 
> Alright, Thanks foy your patient answer, I understood it. Could you please share me the latest training code, my email address is [Byronnar@163.com](mailto:Byronnar@163.com), Thank u su much.

no problem. however, since we are undergoing rebuttal and rn there are some extra experiments in our code, we have to spend some time sorting out the files. we will send u the codes later this day.

**Comment by Byronnar** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Thank you so much! And I have a question, the pretrained weights just is the trained model on ACDC or Synapse? Not in other datasets? Which the pretrained weight used in your paper to get the best results?
> > > 
> > > 
> > > Hi there. Thank u for your question. However, I think there may be a little misunderstanding here. The so-called 'pretrained weights' in this repo is JUST the one we used in the paper to have the results. Unlike Swin-Unet or TransUnet, our model does NOT need any ViT pretrained weights, and it is trained from scratch. We make these two weights public so peers can verify our experimental results. If you would like to use MT-Unet for other datasets, you can train it from scratch by yourself or you can use either uploaded file in this repo as initial weights for your training.
> > 
> > 
> > Alright, Thanks foy your patient answer, I understood it. Could you please share me the latest training code, my email address is [Byronnar@163.com](mailto:Byronnar@163.com), Thank u su much.
> 
> no problem. however, since we are undergoing rebuttal and rn there are some extra experiments in our code, we have to spend some time sorting out the files. we will send u the codes later this day.

Look forward to hearing from you。

**Comment by 939926044** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 太感谢了！我有一个问题，预训练的权重只是 ACDC 或 Synapse 上的训练模型？不在其他数据集中？在您的论文中使用哪个预训练权重以获得最佳结果？
> > > 
> > > 
> > > 你好呀。谢谢你的提问。不过，我觉得这里可能有点误会。这个 repo 中所谓的“预训练权重”就是我们在论文中用来获得结果的权重。与 Swin-Unet 或 TransUnet 不同，我们的模型不需要任何 ViT 预训练权重，它是从头开始训练的。我们将这两个权重公开，以便同行可以验证我们的实验结果。如果您想将 MT-Unet 用于其他数据集，您可以自己从头开始训练，也可以使用此存储库中上传的文件作为训练的初始权重。
> > 
> > 
> > 好的，谢谢你的耐心回答，我明白了。能否分享一下最新的训练代码，我的邮箱是[Byronnar@163.com](mailto:Byronnar@163.com)，非常感谢。
> 
> 没问题。然而，由于我们正在接受反驳并且我们的代码中有一些额外的实验，我们必须花一些时间整理文件。我们将在今天晚些时候向您发送代码。

Hello, can you share the preprocessing and partitioning code of ACDC data set?  I want to verify the performance of MT-UNET on the ACDC dataset.  My email is 939926044sc@gmail.com. Thank you for sharing.

**Comment by Hassan48khan** [comment]
Can you please share the ACDC or Synapse pretrained weights, as the drive link you gave has expired? (ali.hassan@nuaa.edu.cn)
