### ISSUE TITLE
Complete Code for Evaluation

### ISSUE THREAD

**Issue by brewormly** [Dootmaan/MT-UNet#14]
Hi,

I really appreciate your work. In the paper, it is mentioned that you re-trained the models such that you can compare your results to the previous published work. I would be really interested into getting my hands on that code.

**Comment by brewormly** [comment]
And one additional question which came into my mind: From which source did you extract the results of the classic U-Net? I would be very interested how that U-Net was trained.

**Comment by Dootmaan** [comment]
*This issue is closed since no further activity has happened for a while.*
