### ISSUE TITLE
关于testloader

### ISSUE THREAD

**Issue by Andy-Liu5** [Dootmaan/MT-UNet#15]
您好，我在阅读您的源码的时候，发现代码数据准备部分代码缺失了一些，请问您能公开此部分代码吗？

**Comment by Dootmaan** [comment]
hi @Andy-Liu5, thank you for your question. our pre-processing code for ACDC is based on that of Synapse (which is public available in the repo of TransUnet). please leave your email so we can send you the pre-processing code.

**Comment by Andy-Liu5** [comment]
我的email是，liuab522@163.com，非常谢谢您！

**Comment by Dootmaan** [comment]
we have sent the email. pls check your mailbox.
