### ISSUE TITLE
About data processing

### ISSUE THREAD

**Issue by habatua** [Dootmaan/MT-UNet#16]
Thank you for your excellent work!

I want to train the network using my own dataset, and the format of the dataset is nii.  But I have no idea about data processing. Could you offer the code of ACDC dataset processing for my reference？ My email is 769370796@qq.com. Thank you very much!

**Comment by Dootmaan** [comment]
We have sent the code. pls check ur mailbox.

**Comment by wangru1026** [comment]
Hello,@Dootmaan, I also want ACDC processed data sets and lists，can I get it?Thank you very much! My email is
[2336428610@qq.com](mailto:2336428610@qq.com)
