### ISSUE TITLE
About the preprocessed Synapse dataset

### ISSUE THREAD

**Issue by Chenguang-Wang** [Dootmaan/MT-UNet#17]
Great work! I am learning your paper and code recently. 
I sent an email to teh author of TransUnet to request dis dataset but did not get a reply.
Can you share teh preprocessed Synapse dataset with me(wangchenguang@stu.scu.edu.cn)?
Thanks!

**Comment by Chenguang-Wang** [comment]
It is very kind if you can also send the preprocessing code.

**Comment by wangru1026** [comment]
请问有ACDC预处理数据吗？可以分享一下吗？
