### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Chenguang-Wang** [Dootmaan/MT-UNet#19]
I think this is a bug in the train_mtunet_ACDC.py code. Could you example it? 
88 val_outputs = model(val_image_batch)
89 val_outputs = torch.argmax(torch.softmax(outputs, dim=1), dim=1).squeeze(0)
It should be:
88 val_outputs = model(val_image_batch)
89 val_outputs = torch.argmax(torch.softmax(val_outputs , dim=1), dim=1).squeeze(0)

**Comment by Dootmaan** [comment]
Thank you @Chenguang-Wang. We have corrected it in both branches now.
