### ISSUE TITLE
啥时候更新代码阿！

### ISSUE THREAD

**Issue by 459737087** [Dootmaan/MT-UNet#2]

**Comment by Dootmaan** [comment]
The experimental codes are already ready but are not so well organized currently. We plan to upload our code after the paper is accepted. However, if you need to compare with our result we can send a copy of our experimental codes to you.

**Comment by 459737087** [comment]
Thank u !! @Dootmaan

**Comment by jane442** [comment]
Dear Authors:
l am honored to read your paper "MIXED TRANSFORMER U-NET FOR MEDICAL IMAGE SEGMENTATION". This paper has inspired my research and guided my next plan,but I found that you did not provide The complete code , so I sincerely hope that you can provide the complete code. I will be very grateful.

**Comment by 939926044** [comment]
> The experimental codes are already ready but are not so well organized currently. We plan to upload our code upon paper publication. However, if you need to compare with our result right now, we can send a copy of our experimental codes to you.


Hello, I also need your code to compare the experimental results. My email address is   939926044@qq.com   .Thank you!

**Comment by leehaoxuan** [comment]
Dear Authors:：
      I also need your code to compare the experimental results. My email address is 1105920112@qq.com .Thank you!

**Comment by qq274983722** [comment]
Dear Authors:：
I also need your code to compare the experimental results. My email address is 12021131688@stu.nxu.edu.cn .Thank you!

**Comment by chen-yuu** [comment]
Dear Authors:：
I also need your code to compare the experimental results. My email address is 2445746865@qq.com .Thank you!

**Comment by computer-vision-all** [comment]
Dear Authors:：
I also need your code to compare the experimental results. My email address is 2500407015@qq.com .Thank you!

**Comment by 15835550088** [comment]
Dear Authors:
I also need your code to compare the experimental results. My email address is 1686304154@qq.com .Thank you!

**Comment by Byronnar** [comment]
Dear Authors:
I also need your code to compare the experimental results. My email address is byronnar@163.com .Thank u!

**Comment by Byronnar** [comment]
@Dootmaan

**Comment by long123524** [comment]
Dear Authors:
I also need your code to compare the experimental results. My email address is hnzzyxlj@163.com .Thank u!

**Comment by TaoWangzj** [comment]
Dear Authors:：
I also need your code to compare the experimental results. My email address is 2834311289@qq.com.Thank you!

**Comment by weixj1998** [comment]
Dear Authors:：
I need your code to compare the experimental results. My email address is 191861272@qq.com. Thank you very much!

**Comment by umarmubeenkhan** [comment]
Dear authors:
I want to further work on your paper.
can you please share the full code.
email : umarmubeen09@gmail.com

Thank you.

**Comment by Dootmaan** [comment]
Sorry i never noticed that so many people requested the full code in this single issue😂
The complete code is release today so you can fetch the code by yourself now! thank you for your interest in our work.

**Comment by Dootmaan** [comment]
*This issue is closed since no further activity has happened for a while.*
