### ISSUE TITLE
Request for whole code

### ISSUE THREAD

**Issue by tianfengke** [Dootmaan/MT-UNet#22]
I am doing my final year project and try to use the Synapse Dataset for testing. However, the TransUNet code framework is hard to reuse for other network. I met some problems on Synapse Dataset training and testing. I see your code and find it's more understandable and I wonder if you can give me the whole code for reference. Thanks!

**Comment by Dootmaan** [comment]
Hi @tianfengke. can you please be more specific on what kind of code you want? if you mean the pre-processing code u can leave a email here and we will send you the copy.

**Comment by tianfengke** [comment]
Thanks @Dootmaan . I found I missed the testing step in your train_mtunet_Synapse.py file. So actually I found my mistake. However, do you have the lists_ACDC file? It is used in your code, but I don't see the file. Also, I checked the TransUnet github, I only saw the lists_Synapse file.

**Comment by Dootmaan** [comment]
lists_ACDC is a folder similar to lists_Synapse. It can be found in our [pre-processed ACDC dataset](https://drive.google.com/file/d/13qYHNIWTIBzwyFgScORL2RFd002vrPF2/view).

**Comment by tianfengke** [comment]
Thanks!!!

**Comment by Dootmaan** [comment]
*This issue is closed since no further activity has happened for a while.*
