### ISSUE TITLE
good job！ hope to get your help

### ISSUE THREAD

**Issue by yang960526** [Dootmaan/MT-UNet#24]
Good Job，Hope you can provide the comparative test code of Unet on the Synapse dataset，thanks!
zhaoyiyang526@gmail.com

**Comment by Dootmaan** [comment]
you can checkout the full_experiment branch: https://github.com/Dootmaan/MT-UNet/tree/full_experiment

**Comment by yang960526** [comment]
Thank you very much, and good luck with your research

**Comment by Dootmaan** [comment]
*This issue is closed since no further activity has happened for a while.*
