### ISSUE TITLE
Great project. Excuse me, I want to run swin UNET ACDC. How do I get this H5 file,

### ISSUE THREAD

**Issue by zhouyi-git** [Dootmaan/MT-UNet#25]

**Comment by Dootmaan** [comment]
hi @zhouyi-git and thank you for your question. i dont really understand the H5 file you mentioned. do u mean the .yaml file? we use the same YAML file as the original Swin-Unet which can be found at https://github.com/HuCaoFighting/Swin-Unet/blob/main/configs/swin_tiny_patch4_window7_224_lite.yaml

**Comment by Dootmaan** [comment]
*This issue is closed since no further activity has happened for a while.*
