### ISSUE TITLE
 the preprocessed ACDC dataset

### ISSUE THREAD

**Issue by Chy-ang** [Dootmaan/MT-UNet#27]
The preprocessed ACDC dataset is not accessible, could you provide another link？Looking for your reply

**Comment by Dootmaan** [comment]
hi there i double checked the link and im pretty sure it is still accessible. here is the link: https://drive.google.com/file/d/13qYHNIWTIBzwyFgScORL2RFd002vrPF2/view

**Comment by Dootmaan** [comment]
*This issue is closed since no further activity has happened for a while.*
