### ISSUE TITLE
ask help for image visualization

### ISSUE THREAD

**Issue by kathyliu579** [Dootmaan/MT-UNet#28]
Hi i am a starter of this field, and trying to visualize your results saved (such as case0001_pred.nii.gz)  for prediction and gt, just like your paper.  
I cost 2 days to figure out but failed. could you please send me the code of visualizition?
many thanks in advance.

**Comment by Dootmaan** [comment]
hi @kathyliu579. by default, all the predictions are saved as .nii files in ./predictions. To visualize the masks just like the images in the paper, you can use [ITK-Snap](http://www.itksnap.org/pmwiki/pmwiki.php) and import the .nii mask over the original MRI image.

**Comment by kathyliu579** [comment]
cool i appreciate your prompt reply. i will try the tool immediately to see what happens and back to u.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Dootmaan** [comment]
*This issue is closed since no further activity has happened for a while.*
