### ISSUE TITLE
ACDC Preprocessing

### ISSUE THREAD

**Issue by brewormly** [Dootmaan/MT-UNet#29]
The ACDC data set seems to be normalized such that the values are in range [-1, 1]? How did you preprocess the data? I would like to visualize the segmentation performance, but for that I would like to understand how you preprocessed it in the first place. I did not find the information in your paper, nor in this repository or in other issues.

**Comment by Dootmaan** [comment]
Hi @brewormly. thank you for your constant interest in our work.

ACDC preprocess file is modified from that of TransUnet and the main process is no different from that. You can leave your email here so we can send you the ACDC preprocess file.

**Comment by brewormly** [comment]
Hi @Dootmaan, my email is extern.weinberger@tum.de.

Thank you very much for giving those insights!

**Comment by DianDian98** [comment]
Hi @Dootmaan, can I get the ACDC preprocessing file too? 
Thank you so much. My email is whh871002@gmail.com

**Comment by Dootmaan** [comment]
Hi @brewormly and @DianDian98, we have sent the code. Please check your mailbox.

**Comment by DianDian98** [comment]
@Dootmaan OK, thank you. ^^

**Comment by brewormly** [comment]
@Dootmaan Thank you very much!

**Comment by dyysky** [comment]
Hi @Dootmaan, can I get the ACDC preprocessing data?
  Thank you very much!  My email is dyyzsu@163.com

**Comment by Dootmaan** [comment]
Hi @dyysky we have also sent the code to you.

**Comment by wangru1026** [comment]
Hello,@Dootmaan, I also want ACDC processed data sets and lists，can I get it?Thank you very much! My email is 
 2336428610@qq.com

**Comment by Kimmm-pzl** [comment]
Hi @Dootmaan， can I get the ACDC preprocessing file too?
My email is panzlin@mail2.sysu.edu.cn Thank you so much!

**Comment by tpnam0901** [comment]
Hello, @Dootmaan. Could you also send me the ACDC process file? Thank you very much! My email is [tpnam0901@khu.ac.kr](tpnam0901@khu.ac.kr)
