### ISSUE TITLE
Request the complete code

### ISSUE THREAD

**Issue by jane442** [Dootmaan/MT-UNet#3]
Dear Authors:
  l am honored to read your paper "MIXED TRANSFORMER U-NET FOR MEDICAL IMAGE SEGMENTATION". This paper has inspired my research and guided my next plan,but I found that you did not provide The complete code , so I sincerely hope that you can provide the complete code. my mail address is 1458546594@qq.com, Or send me directly， I will be very grateful.

**Comment by Dootmaan** [comment]
> Dear Authors: l am honored to read your paper "MIXED TRANSFORMER U-NET FOR MEDICAL IMAGE SEGMENTATION". This paper has inspired my research and guided my next plan,but I found that you did not provide The complete code , so I sincerely hope that you can provide the complete code. my mail address is [1458546594@qq.com](mailto:1458546594@qq.com), Or send me directly， I will be very grateful.

The code has been sent. Please check your mailbox.
