### ISSUE TITLE
ACDC datasets

### ISSUE THREAD

**Issue by hxp2396** [Dootmaan/MT-UNet#4]
Dear author:
It's very fortunate to read your article "MIXED TRANSFORMER U-NET FOR MEDICAL IMAGE SEGMENTATION". I have a lot of interest in the work of your paper.If available, could you send me your preprocessed ACDC dataset and the complete code?My email is 2396511465@qq.com.Thank you very much!

**Comment by Dootmaan** [comment]
> [2396511465@qq.com](mailto:2396511465@qq.com.Thank)

We have sent the code. Please check your mailbox

**Comment by roar-1128** [comment]
请问可以给我也发一份吗 谢谢！我的邮箱是lxl1041669862@163.com
