### ISSUE TITLE
Question about LV MYO RV values in your paper?

### ISSUE THREAD

**Issue by haideralimughal** [Dootmaan/MT-UNet#45]
Thanks for your outstanding work. Can you share the version of the test.py code that outputs the values of LV MYO RV? Besides, I have successfully run your code but obtained the values of 12 test cases on the ACDC dataset but still struggling to understand how you obtained the LV MYO RV values.

**Comment by Dootmaan** [comment]
Hi @haideralimughal and thank you for your question. The dice and HD95 values of LV MYO RV are already logged in the current test_ACDC.py file. Please refer to line 26 of utils/test_ACDC.py

**Comment by haideralimughal** [comment]
Understood. Thank you.
