### ISSUE TITLE
Image input issue

### ISSUE THREAD

**Issue by sophia-seu** [Dootmaan/MT-UNet#5]
Issue: This code seems to only handle the image input size of 224*224. 

By the way, I have read your paper carefully and I appreciated your work. Could you please provide the complete code that I want to try your method on my research?  I will be grateful if you send your code to my mail. ( 220204674@seu.edu.cn.

Thank you.
Have a good day!

**Comment by Dootmaan** [comment]
hi there. 
we have already sent the code. pls check your mailbox.
