### ISSUE TITLE
About other parts of the code in this paper

### ISSUE THREAD

**Issue by GQBBBB** [Dootmaan/MT-UNet#6]
Hello, 
I am interested in your paper recently, and I want to reproduce the results on my own data set division, but currently only the model structure part of the code. 
If it is convenient, could you please give me the complete code? If possible, please send me email: **guanqb@outlook.com**. 
Thank you for your excellent work.

**Comment by Dootmaan** [comment]
we have sent the code. pls check ur mailbox.
