### ISSUE TITLE
code

### ISSUE THREAD

**Issue by roar-1128** [Dootmaan/MT-UNet#7]
Dear author:
It's very fortunate to read your article "MIXED TRANSFORMER U-NET FOR MEDICAL IMAGE SEGMENTATION". I have a lot of interest in the work of your paper.If available, could you send me your preprocessed ACDC dataset and the complete code?My email is lxl1041669862@163.com.Thank you very much!

**Comment by Dootmaan** [comment]
we have sent the code. pls check ur mailbox.
